---
dependencies:
  meta: ^1.7.0
  path_parsing: ^1.0.1
  pure_ui: ^0.0.1
  xml: '>=6.3.0 <=6.5.0'
description: A dart pure svg library
dev_dependencies:
  test: ^1.26.0
environment:
  sdk: ^3.2.0
name: pure_svg
repository: https://github.com/normidar/pure_svg
topics:
  - svg
  - vector-graphics
version: 0.0.1