---
dependencies:
  meta: ^1.7.0
  path_parsing: ^1.0.1
  pure_ui: ^0.0.1
  xml: ^6.3.0
description: A pure Dart SVG parser and renderer designed for Flutter and Dart projects. This library provides a lightweight, dependency-minimized solution for loading, parsing, and rendering SVG files, making it ideal for custom UI and graphics generation.
dev_dependencies:
  test: ^1.26.0
environment:
  sdk: ^3.2.0
name: pure_svg
repository: https://github.com/normidar/pure_svg
topics:
  - svg
  - vector-graphics
  - pure
  - pure-dart
  - image
version: 0.0.2